[onnx_utils] update torchvision version
mlrun/functions pull request #501
Opened 2022-10-03 07:10 UTC by daniels290813

2022-10-03 17:38 UTC, xsqian approved these changes

2022-10-04 07:32 UTC, guy1992l requested changes

2022-10-04 07:32 UTC, guy1992l commented on onnx_utils/requirements.txt
> +torchvision==0.11.1
why the freezing of the version? if it's not working with 1.10.x we should check it and see why, not freeze version and ignore it.

2022-10-04 07:32 UTC, guy1992l commented on onnx_utils/function.yaml
> +      tf2onnx~=1.9.0 torchvision==0.11.1
why is `torchvision` required?

2022-10-11 05:01 UTC, daniels290813 commented
sorry should be in the description 
running mask-detection demo fails with
```
from torchvision.transforms import InterpolationMode
ImportError: cannot import name 'InterpolationMode' from 'torchvision.transforms' (/opt/conda/lib/python3.7/site-packages/torchvision/transforms/__init__.py)
```

mlrun/ml-models image uses the following versions
```
# pytorch caused cuda download, this guarantees cpu version:
RUN python -m pip install torch==1.7.0+cpu torchvision==0.8.1+cpu \
```
apparently this functionality is added in latter version, check this out
https://blog.csdn.net/prague6695/article/details/120457004

2022-11-07 15:15 UTC, aviaIguazio commented
replace the InterpolationMode import by passing an integer or string that represent the enum value. In older versions it worked with PIL modes and torch decided they want their own. He can still give either "nearest" string or 0 integer and avoid importing the InterpolationMode.

2022-11-07 15:15 UTC, closed without merging