[FIX] PII and Q&A functions
mlrun/functions pull request #653
Opened 2023-08-23 14:06 UTC by GiladShapira94

This PR fix small issues in PII and Q&A functions

2023-08-25 15:50 UTC, guy1992l approved these changes
Excellent :+1:

2023-08-27 09:56 UTC, yonishelach requested changes
Nicely done.
A minor syntax error and please also bump the versions of those functions in the `item.yaml` files.

2023-08-27 09:56 UTC, yonishelach commented on question_answering/question_answering.py
> +    input_path: Union[str.pathlib.Path],
```suggestion
    input_path: Union[str, pathlib.Path],
```

2023-08-27 12:05 UTC, yonishelach approved these changes

2023-08-27 12:05 UTC, merged