[Structured-data-generator] adding structured_data_generator function
mlrun/functions pull request #753
Opened 2023-12-18 15:25 UTC by ZeevRispler

2023-12-20 09:13 UTC, guy1992l requested changes
The `json` in `json_data_generator` is kinda misleading. If the user is not using MLRun then he won't receive a json, but a `list`. I think the function name should be changed to something like structured data generator or something else if you find a better name. The json part is being done via the `returns` where you specified you want to log the returned `list` as a json file.

Also, don't forget the section comments (`#`) :)

2023-12-20 09:13 UTC, guy1992l commented on json_data_generator/json_data_generator.py
> +            # Generate the conversation:
Generate a chunk of data

2023-12-20 09:13 UTC, guy1992l commented on json_data_generator/json_data_generator.py
> +            chunk_data = chunk_data[chunk_data.find("["):chunk_data.rfind("]") + 1]
```suggestion
            # Validate the response for correct python `list` structure
            chunk_data = chunk_data[chunk_data.find("["):chunk_data.rfind("]") + 1]
```

2023-12-20 09:13 UTC, guy1992l commented on json_data_generator/json_data_generator.py
> +            if amount > chunk_size:
Get the size

2023-12-20 09:13 UTC, guy1992l commented on json_data_generator/json_data_generator.py
> +                f"Could not generate a proper json format for the given fields, using given model: {model_name}. Hint: Gpt-4 works for our purpose.")
```suggestion
                f"Could not generate a proper json format for the given fields, using given model: {model_name}. Hint: Gpt-4 works best for most scenarios.")
```

2023-12-20 12:08 UTC, ZeevRispler commented on json_data_generator/function.yaml
> +  - Data Preparation
i think we can do both, i was trying to fit to existing categories

2023-12-20 12:13 UTC, ZeevRispler commented on json_data_generator/json_data_generator.py
> +    return context.get_secret(key)
but you said remove all mlrun context, why use it here?

2023-12-26 10:00 UTC, guy1992l requested changes
minor stuff, the logic and function itself is sweet 💪 Please make sure to use `black` and `isort` to format the code before pushing.

2023-12-26 14:18 UTC, merged